# Generated by Django 2.1.7 on 2019-04-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "animal",
                    models.CharField(
                        choices=[("DOG", "Dog"), ("CAT", "Cat")], max_length=100
                    ),
                ),
                ("nickname", models.CharField(max_length=100)),
            ],
        )
    ]
