site_name: Django REST Framework API Key
site_url: https://florimondmanca.github.io/djangorestframework-api-key
copyright: © 2018-2020 Florimond Manca
theme:
  name: "material"
  palette:
    primary: "red"
    accent: "red"

repo_name: florimondmanca/djangorestframework-api-key
repo_url: https://github.com/florimondmanca/djangorestframework-api-key

nav:
  - Home: index.md
  - User Guide: guide.md
  - Security: security.md
  - Upgrade Guides:
      - "3.0": upgrade/3.0.md
      - "2.0": upgrade/2.0.md
      - "1.4": upgrade/1.4.md
      - "1.0": upgrade/1.0.md
  - Contributing: https://github.com/florimondmanca/djangorestframework-api-key/tree/master/CONTRIBUTING.md
  - Changelog: https://github.com/florimondmanca/djangorestframework-api-key/tree/master/CHANGELOG.md
  - License: https://github.com/florimondmanca/djangorestframework-api-key/tree/master/LICENSE

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.superfences
  - pymdownx.snippets:
      check_paths: true
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
