# Generated by Django 2.2.2 on 2019-06-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='retired',
            field=models.BooleanField(default=False),
        ),
    ]
