# Generated by Django 2.2.2 on 2019-06-29 11:49

from django.db import migrations, models

APP_NAME = "heroes"
MODEL_NAME = "heroapikey"
DEPENDENCIES = [(APP_NAME, "0002_prefix_hashed_key")]


class Migration(migrations.Migration):

    dependencies = DEPENDENCIES

    operations = [
        migrations.RemoveField(model_name=MODEL_NAME, name="id"),
        migrations.AddField(
            model_name=MODEL_NAME,
            name="id",
            field=models.AutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
