# Generated by Django 2.2.2 on 2019-06-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                )
            ],
            options={
                "verbose_name": "EventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEventEvent"
            },
        )
    ]
