# Generated by Django 2.1.1 on 2018-09-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_api_key', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='revoked',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
