# Generated by Django 2.2.1 on 2019-05-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_api_key', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
