
# Generated by Django 2.1.7 on 2019-04-25 08:57

from django.db import migrations, models
import django.db.models.deletion
import rest_framework_api_key.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_api_key', '0002_auto_20190529_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKeyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the API key group', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'API Key Group',
                'verbose_name_plural': 'API Key Groups',
            },
        ),
        migrations.CreateModel(
            name='EndpointPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='A regex matching the URL path. This should begin with / and include the version, eg "/v1/time"', max_length=100, validators=[rest_framework_api_key.validators.validate_regex_pattern])),
                ('method', models.CharField(choices=[('CONNECT', 'CONNECT'), ('DELETE', 'DELETE'), ('GET', 'GET'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS'), ('PATCH', 'PATCH'), ('POST', 'POST'), ('PUT', 'PUT'), ('TRACE', 'TRACE')], default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Endpoint Permission',
                'verbose_name_plural': 'Endpoint Permissions',
            },
        ),
        migrations.AlterModelOptions(
            name='apikey',
            options={'ordering': ('-created',), 'verbose_name': 'API Key', 'verbose_name_plural': 'API Keys'},
        ),
        migrations.AlterUniqueTogether(
            name='endpointpermission',
            unique_together={('path', 'method')},
        ),
        migrations.AddField(
            model_name='apikeygroup',
            name='endpoint_permissions',
            field=models.ManyToManyField(related_name='api_key_groups', to='rest_framework_api_key.EndpointPermission'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_framework_api_key.APIKeyGroup'),
        ),
    ]