# Generated by Django 2.1.1 on 2018-09-24 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_api_key', '0002_auto_20180922_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikey',
            old_name='key',
            new_name='token',
        ),
    ]
