# Generated by Django 2.1.7 on 2019-04-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_api_key', '0003_auto_20190425_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeygroup',
            name='endpoint_permissions',
            field=models.ManyToManyField(blank=True, related_name='api_key_groups', to='rest_framework_api_key.EndpointPermission'),
        ),
    ]
