# Generated by Django 2.1.1 on 2018-09-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_api_key', '0003_auto_20180924_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='hashed_token',
            field=models.CharField(help_text='A public hash of the token, generated using the secret key (which is given to the client and not kept in database).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='token',
            field=models.CharField(help_text='A public, unique identifier for this API key.', max_length=40, unique=True),
        ),
    ]
