# Generated by Django 2.2.2 on 2019-06-30 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("rest_framework_api_key", "0004_prefix_hashed_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scope",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=64)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.ContentType",
                        verbose_name="content type",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "content_type__app_label",
                    "content_type__model",
                    "code",
                ],
                "unique_together": {("content_type", "code")},
            },
        ),
        migrations.AddField(
            model_name="apikey",
            name="scopes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific scopes for this API key",
                related_name="apikey_set",
                related_query_name="apikey",
                to="rest_framework_api_key.Scope",
                verbose_name="scopes",
            ),
        ),
    ]
