# Generated by Django 2.1.7 on 2019-06-21 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_api_key', '0004_auto_20190425_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'ordering': ('-created',), 'verbose_name': 'API key', 'verbose_name_plural': 'API keys'},
        ),
        migrations.AlterModelOptions(
            name='apikeygroup',
            options={'verbose_name': 'API key group', 'verbose_name_plural': 'API key groups'},
        ),
        migrations.AlterModelOptions(
            name='endpointpermission',
            options={'verbose_name': 'Endpoint permission', 'verbose_name_plural': 'Endpoint permissions'},
        ),
    ]
