# Generated by Django 3.2.11 on 2022-01-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0003_alter_hero_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroapikey',
            name='hashed_key',
            field=models.CharField(editable=False, max_length=150),
        ),
    ]
