#!/bin/sh -e

if [ -d 'dist' ] ; then
    rm -r dist
fi

if [ -d 'build' ] ; then
    rm -r build
fi

if [ -d 'site' ] ; then
    rm -r site
fi

if [ -d 'htmlcov' ] ; then
    rm -r htmlcov
fi

if [ -d "src/djangorestframework_api_key.egg-info" ] ; then
    rm -r src/djangorestframework_api_key.egg-info
fi

find src/rest_framework_api_key -type f -name "*.py[co]" -delete
find src/rest_framework_api_key -type d -name __pycache__ -delete
