#!/bin/sh -e

if [ -z $CI ] ; then
  echo "Creating virtual environment in 'venv/'..."
  python -m venv venv
fi

source scripts/env

set -x

${PREFIX}python -m pip install -U pip
${PREFIX}python -m pip install -r requirements.txt

if [ ! -z $DJANGO_VERSION ]; then
  ${PREFIX}python -m pip install django==$DJANGO_VERSION
fi

set +x

echo
echo "Success!"

if [ -z $CI ]; then
  echo "You can now activate your virtual environment using:"
  echo "source ${PREFIX}activate"
fi
