#!/bin/sh -e

. scripts/env

export SOURCE_FILES="src/rest_framework_api_key test_project tests"

set -x

${PREFIX}autoflake --in-place --recursive $SOURCE_FILES
${PREFIX}seed-isort-config --application-directories=src
${PREFIX}isort $SOURCE_FILES
${PREFIX}black --target-version=py36 $SOURCE_FILES
