#!/bin/sh -e

source scripts/env

export TEST_SOURCE_FILES=$(tr "\n" " " << EOF
tests/conftest.py
EOF
)

export SOURCE_FILES="src/rest_framework_api_key $TEST_SOURCE_FILES"

set -x

${PREFIX}autoflake --in-place --recursive $SOURCE_FILES
${PREFIX}seed-isort-config --application-directories=src
${PREFIX}isort --project=rest_framework_api_key --recursive --apply $SOURCE_FILES
${PREFIX}black --target-version=py36 $SOURCE_FILES
